# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "plox!"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "pluto."

# Tagline section text
tagline: >-
    hi.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-twitter"
      text: "twitter"
      url: "https://twitter.com/wtfisplox"
      alt: "twitter"
      title: "twitter"
      target: "_blank"
  - link:
      icon: "fa-brands fa-bluesky"
      text: "bluesky"
      url: "https://bsky.app/profile/wtfisplox.foxwitch.tech"
      alt: "bluesky"
      title: "bluesky"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
#socials:
#  - social:
#      icon: "fa-brands fa-medium"
#      url: "https://blog.zhgchg.li"
#      title: "ZhgChgLi's Medium"
#      alt: "ZhgChgLi's Medium"
#      target: "_blank"


# Footer text
#footer: >
#    Hi there! Follow me on Medium or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
#copyright: >
#  © 2024  <a href="https://zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
